"""empty message

Revision ID: 82e3b75f46d2
Revises: e97a1704833e
Create Date: 2021-06-09 21:20:25.745074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e3b75f46d2'
down_revision = 'e97a1704833e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('category', sa.Enum('option_1', 'option_2', 'option_3', name='ad_category'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad', 'category')
    # ### end Alembic commands ###
